### ISSUE TITLE
When socket connection to Twitter stream API is broken, exception is thrown

### ISSUE THREAD

**Issue by trygve-lie** [webrebels/web-rebels-2014#33]
If the socket connection to the Twitter stream API is broken, the Twitter plugin throws an exception we do not catch. This causes server to go down due to the crash fast strategy. 

We should catch this exception.

```
[05/15 12:16:52 GMT+0200][err] Error: Forbidden
[05/15 12:16:52 GMT+0200][err]     at SendStream.error (/opt/run/snapshot/package/node_modules/serve-static/node_modules/send/lib/send.js:170:16)
[05/15 12:16:52 GMT+0200][err]     at SendStream.pipe (/opt/run/snapshot/package/node_modules/serve-static/node_modules/send/lib/send.js:365:52)
[05/15 12:16:52 GMT+0200][err]     at Layer.staticMiddleware [as handle] (/opt/run/snapshot/package/node_modules/serve-static/index.js:93:8)
[05/15 12:16:52 GMT+0200][err]     at trim_prefix (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:240:15)
[05/15 12:16:52 GMT+0200][err]     at /opt/run/snapshot/package/node_modules/express/lib/router/index.js:208:9
[05/15 12:16:52 GMT+0200][err]     at Function.proto.process_params (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:269:12)
[05/15 12:16:52 GMT+0200][err]     at next (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:199:19)
[05/15 12:16:52 GMT+0200][err]     at Layer.compress [as handle] (/opt/run/snapshot/package/node_modules/compression/index.js:162:5)
[05/15 12:16:52 GMT+0200][err]     at trim_prefix (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:240:15)
[05/15 12:16:52 GMT+0200][err]     at /opt/run/snapshot/package/node_modules/express/lib/router/index.js:208:9
[05/19 21:56:56 GMT+0200][err] error: shutdown - server taken down by force due to a uncaughtException
[05/19 21:56:56 GMT+0200][err] error: socket hang up
[05/19 21:56:56 GMT+0200][err] error: Error: socket hang up
[05/19 21:56:56 GMT+0200][err]     at SecurePair.error (tls.js:1013:23)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.CryptoStream._done (tls.js:705:22)
[05/19 21:56:56 GMT+0200][err]     at CleartextStream.read [as _read] (tls.js:496:24)
[05/19 21:56:56 GMT+0200][err]     at CleartextStream.Readable.read (_stream_readable.js:320:10)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.g (events.js:180:16)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.EventEmitter.emit (events.js:117:20)
[05/19 21:56:56 GMT+0200][err]     at finishMaybe (_stream_writable.js:356:12)
[05/19 21:56:56 GMT+0200][err]     at endWritable (_stream_writable.js:363:3)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.Writable.end (_stream_writable.js:341:5)
[05/19 21:56:56 GMT+0200][err]     at EncryptedStream.CryptoStream.end (tls.js:643:31)
[05/19 21:56:56 GMT+0200][err]     at Socket.onend (_stream_readable.js:483:10)
[05/19 21:56:56 GMT+0200][err] error: uncaughtException: socket hang up date=Mon May 19 2014 19:56:56 GMT+0000 (UTC), pid=65908, uid=103, gid=65534, cwd=/opt/run/snapshot/package, execPath=/opt/engines/node/v0.10.25/bin/node, version=v0.10.25, argv=[node, /opt/run/snapshot/package/bin/server.js], rss=110100480, heapTotal=52032256, heapUsed=23058344, loadavg=[0, 0, 0], uptime=357320, trace=[column=23, file=tls.js, function=SecurePair.error, line=1013, method=error, native=false, column=22, file=tls.js, function=EncryptedStream.CryptoStream._done, line=705, method=CryptoStream._done, native=false, column=24, file=tls.js, function=CleartextStream.read [as _read], line=496, method=read [as _read], native=false, column=10, file=_stream_readable.js, function=CleartextStream.Readable.read, line=320, method=Readable.read, native=false, column=47, file=tls.js, function=EncryptedStream.onCryptoStreamFinish, line=301, method=onCryptoStreamFinish, native=false, column=16, file=events.js, function=EncryptedStream.g, line=180, method=g, native=false, column=20, file=events.js, function=EncryptedStream.EventEmitter.emit, line=117, method=EventEmitter.emit, native=false, column=12, file=_stream_writable.js, function=finishMaybe, line=356, method=null, native=false, column=3, file=_stream_writable.js, function=endWritable, line=363, method=null, native=false, column=5, file=_stream_writable.js, function=EncryptedStream.Writable.end, line=341, method=Writable.end, native=false, column=31, file=tls.js, function=EncryptedStream.CryptoStream.end, line=643, method=CryptoStream.end, native=false, column=10, file=_stream_readable.js, function=Socket.onend, line=483, method=onend, native=false], stack=[Error: socket hang up,     at SecurePair.error (tls.js:1013:23),     at EncryptedStream.CryptoStream._done (tls.js:705:22),     at CleartextStream.read [as _read] (tls.js:496:24),     at CleartextStream.Readable.read (_stream_readable.js:320:10),     at EncryptedStream.onCryptoStreamFinish (tls.js:301:47),     at EncryptedStream.g (events.js:180:16),     at EncryptedStream.EventEmitter.emit (events.js:117:20),     at finishMaybe (_stream_writable.js:356:12),     at endWritable (_stream_writable.js:363:3),     at EncryptedStream.Writable.end (_stream_writable.js:341:5),     at EncryptedStream.CryptoStream.end (tls.js:643:31),     at Socket.onend (_stream_readable.js:483:10)]
[05/19 22:00:25 GMT+0200][err] error: twitter - tracker could not query twitter
```

**Comment by Andersos** [comment]
Hmm, I'm taking the liberty to close this since we are doing webrebels/web-rebels-2015/issues/6
